import {
  fontFamilyToCss,
  hexToRgba,
  shadowToCss,
  type FormAppearance,
  type FormSchema,
} from "@/domain/form-schema";

function standaloneCss(appearance: FormAppearance): string {
  const colors = appearance.colors;
  const accentRing = hexToRgba(colors.accent, 0.22);
  const successBg = hexToRgba(colors.success, 0.12);
  const successBorder = hexToRgba(colors.success, 0.35);
  const dangerBg = hexToRgba(colors.danger, 0.1);
  const dangerBorder = hexToRgba(colors.danger, 0.35);

  return `/* Generated by Formly */
.formly-page {
  margin: 0;
  padding: 2rem 1rem;
  background: ${colors.pageBackground};
}

.formly-sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

.formly-form {
  --formly-bg: ${colors.formBackground};
  --formly-input-bg: ${colors.inputBackground};
  --formly-border: ${colors.border};
  --formly-text: ${colors.text};
  --formly-muted: ${colors.muted};
  --formly-accent: ${colors.accent};
  --formly-accent-hover: ${colors.accentHover};
  --formly-submit-text: ${colors.submitText};
  --formly-danger: ${colors.danger};
  --formly-success: ${colors.success};
  --formly-radius: ${appearance.radius.control}px;
  --formly-radius-form: ${appearance.radius.form}px;
  --formly-shadow: ${shadowToCss(appearance.shadow)};

  box-sizing: border-box;
  max-width: ${appearance.spacing.maxWidth}px;
  margin: 0 auto;
  padding: ${appearance.spacing.padding}px;
  color: var(--formly-text);
  background: var(--formly-bg);
  border: 1px solid var(--formly-border);
  border-radius: var(--formly-radius-form);
  box-shadow: var(--formly-shadow);
  font-family: ${fontFamilyToCss(appearance.typography.fontFamily)};
  font-size: ${appearance.typography.bodySize}px;
  line-height: 1.5;
}

.formly-form *,
.formly-form *::before,
.formly-form *::after {
  box-sizing: border-box;
}

.formly-form-header {
  margin-bottom: 1.25rem;
}

.formly-form-title {
  margin: 0;
  font-size: ${appearance.typography.titleSize}px;
  font-weight: 650;
  letter-spacing: -0.02em;
}

.formly-form-description {
  margin: 0.4rem 0 0;
  color: var(--formly-muted);
  font-size: 0.95rem;
}

.formly-fields {
  display: grid;
  gap: ${appearance.spacing.fieldGap}px;
}

.formly-field,
.formly-fieldset {
  margin: 0;
  padding: 0;
  border: 0;
  min-width: 0;
}

.formly-label {
  display: block;
  margin-bottom: 0.4rem;
  font-size: 0.9rem;
  font-weight: 600;
}

.formly-required {
  color: var(--formly-danger);
}

.formly-description {
  margin: 0 0 0.5rem;
  color: var(--formly-muted);
  font-size: 0.82rem;
}

.formly-control {
  display: block;
  width: 100%;
  min-height: 2.5rem;
  padding: 0.55rem 0.75rem;
  color: var(--formly-text);
  background: var(--formly-input-bg);
  border: 1px solid var(--formly-border);
  border-radius: var(--formly-radius);
  font: inherit;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
}

textarea.formly-control {
  min-height: 7rem;
  resize: vertical;
}

.formly-control:focus,
.formly-control:focus-visible {
  outline: none;
  border-color: var(--formly-accent);
  box-shadow: 0 0 0 3px ${accentRing};
}

.formly-field.is-invalid .formly-control,
.formly-fieldset.is-invalid .formly-control {
  border-color: var(--formly-danger);
}

.formly-options {
  display: grid;
  gap: 0.5rem;
}

.formly-option {
  display: flex;
  align-items: center;
  gap: 0.55rem;
  font-size: 0.92rem;
}

.formly-error {
  margin: 0.4rem 0 0;
  color: var(--formly-danger);
  font-size: 0.8rem;
}

.formly-actions {
  margin-top: 0.25rem;
}

.formly-submit {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 2.5rem;
  padding: 0.55rem 1.1rem;
  color: var(--formly-submit-text);
  background: var(--formly-accent);
  border: 0;
  border-radius: var(--formly-radius);
  font: inherit;
  font-weight: 600;
  cursor: pointer;
  transition: background-color 0.15s ease;
}

.formly-submit:hover {
  background: var(--formly-accent-hover);
}

.formly-submit:focus-visible {
  outline: 2px solid var(--formly-accent);
  outline-offset: 2px;
}

.formly-submit:disabled {
  opacity: 0.65;
  cursor: not-allowed;
}

@media (prefers-reduced-motion: reduce) {
  .formly-control,
  .formly-submit {
    transition: none;
  }
}

.formly-success,
.formly-form-error {
  margin-top: 1rem;
  padding: 0.85rem 1rem;
  border-radius: var(--formly-radius);
  font-size: 0.9rem;
}

.formly-success {
  color: var(--formly-success);
  background: ${successBg};
  border: 1px solid ${successBorder};
}

.formly-form-error {
  color: var(--formly-danger);
  background: ${dangerBg};
  border: 1px solid ${dangerBorder};
}

@media (max-width: 640px) {
  .formly-form {
    padding: 1.1rem;
  }

  .formly-form-title {
    font-size: 1.2rem;
  }
}
`;
}

function tailwindCompanionCss(appearance: FormAppearance): string {
  const colors = appearance.colors;
  const accentRing = hexToRgba(colors.accent, 0.22);
  const successBg = hexToRgba(colors.success, 0.12);
  const successBorder = hexToRgba(colors.success, 0.35);
  const dangerBg = hexToRgba(colors.danger, 0.1);
  const dangerBorder = hexToRgba(colors.danger, 0.35);

  return `/* Generated by Formly — Tailwind companion stylesheet
 * Visual layout and colors come from Tailwind utility classes on the HTML.
 * Keep this file for screen-reader helpers and JavaScript validation states.
 * Include Tailwind CSS in the host page (or use the Play CDN in the combined HTML).
 * Production sites should use a built Tailwind pipeline, not the Play CDN.
 */
.formly-sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}

.formly-control:focus,
.formly-control:focus-visible {
  outline: none;
  border-color: ${colors.accent};
  box-shadow: 0 0 0 3px ${accentRing};
}

.formly-field.is-invalid .formly-control,
.formly-fieldset.is-invalid .formly-control {
  border-color: ${colors.danger};
}

.formly-submit:hover {
  background: ${colors.accentHover};
}

.formly-submit:focus-visible {
  outline: 2px solid ${colors.accent};
  outline-offset: 2px;
}

.formly-submit:disabled {
  opacity: 0.65;
  cursor: not-allowed;
}

.formly-success {
  color: ${colors.success};
  background: ${successBg};
  border-color: ${successBorder};
}

.formly-form-error {
  color: ${colors.danger};
  background: ${dangerBg};
  border-color: ${dangerBorder};
}

@media (prefers-reduced-motion: reduce) {
  .formly-control,
  .formly-submit {
    transition: none;
  }
}
`;
}

/**
 * Standalone form styles. Independent from Formly application CSS.
 */
export function generateFormCss(schema: FormSchema): string {
  if (schema.appearance.cssFlavor === "tailwind") {
    return tailwindCompanionCss(schema.appearance);
  }

  return standaloneCss(schema.appearance);
}
