import type { FormField, FormSchema } from "@/domain/form-schema";

import { toJsLiteral } from "@/features/code/generators/escape";

interface GeneratedFieldConfig {
  name: string;
  type: FormField["type"] | "checkbox-group";
  required: boolean;
  validation: FormField["validation"];
}

function toFieldConfig(field: FormField): GeneratedFieldConfig | null {
  if (field.type === "submit") {
    return null;
  }

  if (field.type === "checkbox" && field.options.length > 0) {
    return {
      name: field.name,
      type: "checkbox-group",
      required: field.required,
      validation: field.validation,
    };
  }

  return {
    name: field.name,
    type: field.type,
    required: field.required,
    validation: field.validation,
  };
}

export function generateFormJavaScript(schema: FormSchema): string {
  const fields = schema.fields
    .map((field) => toFieldConfig(field))
    .filter((field): field is GeneratedFieldConfig => field !== null);

  const hasAction = schema.submission.action.trim().length > 0;
  const messages = {
    required: "This field is required.",
    minLength: "Too few characters.",
    maxLength: "Too many characters.",
    min: "Value is below the minimum.",
    max: "Value is above the maximum.",
    pattern: "The format is invalid.",
    email: "Enter a valid email address.",
    number: "Enter a valid number.",
    successWithSubmit: "Form is valid and will be submitted.",
    successLocal: "Form is valid. No action URL was configured, so nothing was sent.",
    submitError: "Please fix the highlighted fields.",
  };

  return `/* Generated by Formly — standalone client validation */
(function () {
  "use strict";

  var fields = ${toJsLiteral(fields)};
  var messages = ${toJsLiteral(messages)};
  var hasAction = ${toJsLiteral(hasAction)};

  function $all(selector, root) {
    return Array.prototype.slice.call((root || document).querySelectorAll(selector));
  }

  function isEmpty(value) {
    return String(value || "").trim() === "";
  }

  function namedControls(form, name) {
    return $all("input, select, textarea", form).filter(function (element) {
      return element.name === name;
    });
  }

  function getFieldRoot(form, name) {
    var nodes = $all("[data-field-name]", form);
    for (var i = 0; i < nodes.length; i += 1) {
      if (nodes[i].getAttribute("data-field-name") === name) {
        return nodes[i];
      }
    }
    return null;
  }

  function getErrorNode(form, name) {
    var nodes = $all("[data-error-for]", form);
    for (var i = 0; i < nodes.length; i += 1) {
      if (nodes[i].getAttribute("data-error-for") === name) {
        return nodes[i];
      }
    }
    return null;
  }

  function getValue(form, field) {
    var controls = namedControls(form, field.name);

    if (field.type === "checkbox") {
      return controls.length > 0 ? !!controls[0].checked : false;
    }

    if (field.type === "checkbox-group") {
      return controls
        .filter(function (input) {
          return input.checked;
        })
        .map(function (input) {
          return input.value;
        });
    }

    if (field.type === "radio") {
      var checked = controls.find(function (input) {
        return input.checked;
      });
      return checked ? checked.value : "";
    }

    return controls.length > 0 ? controls[0].value : "";
  }

  function setFieldError(form, field, code) {
    var root = getFieldRoot(form, field.name);
    var error = getErrorNode(form, field.name);
    var controls = namedControls(form, field.name);
    var invalid = !!code;

    if (root) {
      if (invalid) {
        root.classList.add("is-invalid");
      } else {
        root.classList.remove("is-invalid");
      }
    }

    controls.forEach(function (control) {
      if (invalid) {
        control.setAttribute("aria-invalid", "true");
      } else {
        control.removeAttribute("aria-invalid");
      }
    });

    if (error) {
      if (invalid) {
        error.hidden = false;
        error.setAttribute("role", "alert");
        error.textContent = messages[code] || messages.required;
      } else {
        error.hidden = true;
        error.removeAttribute("role");
        error.textContent = "";
      }
    }
  }

  function validateField(form, field) {
    var value = getValue(form, field);

    if (field.type === "checkbox") {
      if (field.required && !value) {
        return "required";
      }
      return null;
    }

    if (field.type === "checkbox-group") {
      if (field.required && (!value || value.length === 0)) {
        return "required";
      }
      return null;
    }

    var text = String(value || "");

    if (field.required && isEmpty(text)) {
      return "required";
    }

    if (isEmpty(text)) {
      return null;
    }

    if (field.type === "email") {
      var emailPattern = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;
      if (!emailPattern.test(text)) {
        return "email";
      }
    }

    if (field.type === "number") {
      var numeric = Number(text);
      if (!isFinite(numeric)) {
        return "number";
      }
      if (field.validation.min != null && numeric < field.validation.min) {
        return "min";
      }
      if (field.validation.max != null && numeric > field.validation.max) {
        return "max";
      }
    }

    if (
      (field.type === "text" || field.type === "email" || field.type === "textarea") &&
      field.validation.minLength != null &&
      text.length < field.validation.minLength
    ) {
      return "minLength";
    }

    if (
      (field.type === "text" || field.type === "email" || field.type === "textarea") &&
      field.validation.maxLength != null &&
      text.length > field.validation.maxLength
    ) {
      return "maxLength";
    }

    if (
      (field.type === "text" || field.type === "email" || field.type === "textarea") &&
      field.validation.pattern
    ) {
      try {
        var regex = new RegExp(field.validation.pattern);
        if (!regex.test(text)) {
          return "pattern";
        }
      } catch (error) {
        return "pattern";
      }
    }

    return null;
  }

  function validateForm(form) {
    var valid = true;
    fields.forEach(function (field) {
      var code = validateField(form, field);
      setFieldError(form, field, code);
      if (code) {
        valid = false;
      }
    });
    return valid;
  }

  function clearStatus(form) {
    var success = form.querySelector("[data-formly-success]");
    var error = form.querySelector("[data-formly-form-error]");
    if (success) {
      success.hidden = true;
      success.textContent = "";
    }
    if (error) {
      error.hidden = true;
      error.textContent = "";
    }
  }

  function showStatus(form, type, message) {
    clearStatus(form);
    var node = form.querySelector(
      type === "success" ? "[data-formly-success]" : "[data-formly-form-error]",
    );
    if (node) {
      node.hidden = false;
      node.setAttribute("role", type === "success" ? "status" : "alert");
      node.textContent = message;
    }
  }

  function bindForm(form) {
    form.addEventListener("submit", function (event) {
      clearStatus(form);
      var isValid = validateForm(form);

      if (!isValid) {
        event.preventDefault();
        showStatus(form, "error", messages.submitError);
        return;
      }

      if (!hasAction) {
        event.preventDefault();
        showStatus(form, "success", messages.successLocal);
        return;
      }

      showStatus(form, "success", messages.successWithSubmit);
    });

    form.addEventListener("input", function (event) {
      var target = event.target;
      if (!target || !target.name) {
        return;
      }
      var field = fields.find(function (item) {
        return item.name === target.name;
      });
      if (field) {
        setFieldError(form, field, validateField(form, field));
      }
    });

    form.addEventListener("change", function (event) {
      var target = event.target;
      if (!target || !target.name) {
        return;
      }
      var field = fields.find(function (item) {
        return item.name === target.name;
      });
      if (field) {
        setFieldError(form, field, validateField(form, field));
      }
    });
  }

  function init() {
    $all("[data-formly-form]").forEach(bindForm);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
`;
}
