/**
 * Standalone form styles. Independent from Formly application CSS.
 */
export function generateFormCss(): string {
  return `/* Generated by Formly */
.formly-form {
  --formly-bg: #ffffff;
  --formly-border: #d8d8e0;
  --formly-text: #16161d;
  --formly-muted: #6b6b76;
  --formly-accent: #4c6fff;
  --formly-accent-hover: #3b5cf0;
  --formly-danger: #d64550;
  --formly-success: #1f9d6a;
  --formly-radius: 10px;
  --formly-shadow: 0 8px 28px -12px rgba(20, 20, 40, 0.18);

  box-sizing: border-box;
  max-width: 40rem;
  margin: 0 auto;
  padding: 1.5rem;
  color: var(--formly-text);
  background: var(--formly-bg);
  border: 1px solid var(--formly-border);
  border-radius: calc(var(--formly-radius) + 4px);
  box-shadow: var(--formly-shadow);
  font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
  line-height: 1.5;
}

.formly-form *,
.formly-form *::before,
.formly-form *::after {
  box-sizing: border-box;
}

.formly-form-header {
  margin-bottom: 1.25rem;
}

.formly-form-title {
  margin: 0;
  font-size: 1.35rem;
  font-weight: 650;
  letter-spacing: -0.02em;
}

.formly-form-description {
  margin: 0.4rem 0 0;
  color: var(--formly-muted);
  font-size: 0.95rem;
}

.formly-fields {
  display: grid;
  gap: 1rem;
}

.formly-field,
.formly-fieldset {
  margin: 0;
  padding: 0;
  border: 0;
  min-width: 0;
}

.formly-label {
  display: block;
  margin-bottom: 0.4rem;
  font-size: 0.9rem;
  font-weight: 600;
}

.formly-required {
  color: var(--formly-danger);
}

.formly-description {
  margin: 0 0 0.5rem;
  color: var(--formly-muted);
  font-size: 0.82rem;
}

.formly-control {
  display: block;
  width: 100%;
  min-height: 2.5rem;
  padding: 0.55rem 0.75rem;
  color: var(--formly-text);
  background: #fafafc;
  border: 1px solid var(--formly-border);
  border-radius: var(--formly-radius);
  font: inherit;
  transition: border-color 0.15s ease, box-shadow 0.15s ease;
}

textarea.formly-control {
  min-height: 7rem;
  resize: vertical;
}

.formly-control:focus {
  outline: none;
  border-color: var(--formly-accent);
  box-shadow: 0 0 0 3px rgba(76, 111, 255, 0.22);
}

.formly-field.is-invalid .formly-control,
.formly-fieldset.is-invalid .formly-control {
  border-color: var(--formly-danger);
}

.formly-options {
  display: grid;
  gap: 0.5rem;
}

.formly-option {
  display: flex;
  align-items: center;
  gap: 0.55rem;
  font-size: 0.92rem;
}

.formly-error {
  margin: 0.4rem 0 0;
  color: var(--formly-danger);
  font-size: 0.8rem;
}

.formly-actions {
  margin-top: 0.25rem;
}

.formly-submit {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 2.5rem;
  padding: 0.55rem 1.1rem;
  color: #ffffff;
  background: var(--formly-accent);
  border: 0;
  border-radius: var(--formly-radius);
  font: inherit;
  font-weight: 600;
  cursor: pointer;
  transition: background-color 0.15s ease;
}

.formly-submit:hover {
  background: var(--formly-accent-hover);
}

.formly-submit:disabled {
  opacity: 0.65;
  cursor: not-allowed;
}

.formly-success,
.formly-form-error {
  margin-top: 1rem;
  padding: 0.85rem 1rem;
  border-radius: var(--formly-radius);
  font-size: 0.9rem;
}

.formly-success {
  color: #0f5132;
  background: #e8f8f0;
  border: 1px solid #b7e4cd;
}

.formly-form-error {
  color: #842029;
  background: #fdecef;
  border: 1px solid #f1c0c5;
}

@media (max-width: 640px) {
  .formly-form {
    padding: 1.1rem;
    border-radius: var(--formly-radius);
  }

  .formly-form-title {
    font-size: 1.2rem;
  }
}
`;
}
