import { describe, expect, it } from "vitest";

import { createEmptyForm, createField } from "@/domain/form-schema";
import { generateFormCode } from "@/features/code/generators/generate-form-code";

describe("generateFormCode", () => {
  it("returns html, css, javascript, and a combined document", () => {
    const schema = createEmptyForm("Feedback");
    const text = createField("text");
    schema.fields = [text, ...schema.fields];
    schema.submission = {
      action: "https://example.com/feedback",
      method: "POST",
    };

    const code = generateFormCode(schema);

    expect(code.html).toContain("data-formly-form");
    expect(code.css).toContain(".formly-form");
    expect(code.javascript).toContain("Generated by Formly");
    expect(code.combined).toContain("<!doctype html>");
    expect(code.combined).toContain("<style>");
    expect(code.combined).toContain("<script>");
    expect(code.combined).toContain("https://example.com/feedback");
  });
});
