import { describe, expect, it } from "vitest";

import { createEmptyForm, createField } from "@/domain/form-schema";
import { generateFormCode } from "@/features/code/generators/generate-form-code";

describe("generateFormCode", () => {
  it("returns html, css, javascript, and a combined document", () => {
    const schema = createEmptyForm("Feedback");
    const text = createField("text");
    schema.fields = [text, ...schema.fields];
    schema.submission = {
      action: "https://example.com/feedback",
      method: "POST",
    };

    const code = generateFormCode(schema);

    expect(code.html).toContain("data-formly-form");
    expect(code.css).toContain(".formly-form");
    expect(code.javascript).toContain("Generated by Formly");
    expect(code.combined).toContain("<!doctype html>");
    expect(code.combined).toContain("formly-page");
    expect(code.combined).toContain("<style>");
    expect(code.combined).toContain("<script>");
    expect(code.combined).toContain("https://example.com/feedback");
    expect(code.css).toContain(".formly-sr-only");
    expect(code.html).toContain("formly-sr-only");
  });

  it("includes the Tailwind Play CDN in combined HTML when flavor is tailwind", () => {
    const schema = createEmptyForm("Tailwind Form");
    const text = createField("text");
    schema.fields = [text, ...schema.fields];
    schema.appearance.cssFlavor = "tailwind";

    const code = generateFormCode(schema);

    expect(code.combined).toContain("cdn.tailwindcss.com");
    expect(code.html).toContain("bg-[#");
    expect(code.css).toContain("Tailwind companion stylesheet");
  });
});
